# Generated by Django 5.1.1 on 2024-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imageupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='predicted_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
