# Generated by Django 5.1.1 on 2025-03-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_imageupload_onfidence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imageupload",
            old_name="onfidence",
            new_name="confidence",
        ),
    ]
